export const imgPath = {
  path: [
    require('../assets/images/_Status_bar.png'),
    require('../assets/images/_Status_barWhite.png'),
    require('../assets/images/indicator.png'),
    require('../assets/images/back.png'),
    require('../assets/images/plus.png'),
    require('../assets/images/airplain.png'),
    require('../assets/images/dots.png'),
    require('../assets/images/noChat.png'),
    require('../assets/images/background.png'),
    require('../assets/images/github.png'),
    require('../assets/images/instagram.png'),
  ],
  profile: [
    require('../assets/images/myprofile.png'),
    require('../assets/images/profile1.png'),
    require('../assets/images/profile2.png'),
    require('../assets/images/profile3.png'),
    require('../assets/images/profile4.png'),
    require('../assets/images/profile5.png'),
    require('../assets/images/profile6.png'),
    require('../assets/images/profile7.png'),
    require('../assets/images/profile8.png'),
    require('../assets/images/profile9.png'),
  ],
}
